### ISSUE TITLE
Окончательно разобраться с документацией

### ISSUE THREAD

**Issue by AIexandrKotov** [SunSerega/POCGL#4]
## Эта issue будет закрыта, когда будет окончательно доработана документация.

OpenCLABC (строка 385):
Вариант выполнять очередь несколько раз, как в случае с .Clone, нередко не подходит, потому что это удваивает затраты производительности

Что, прости, удваивает? Можно конкретнее? Время, память GPU?

**Comment by SunSerega** [comment]
Обычно время GPU, может и память. `.Clone` создаёт полную копию очереди, поэтому при выполнении обоих - обе выполняются с 0.

**Comment by SunSerega** [comment]
- [x] В разделе терминов криво объяснялось что такое экземпляр.
Было "Экземпляр — переменная класса или записи".
Пока что сделал "Экземпляр класса T — переменная типа T, значение которой НЕ nil".
Но всё равно плохо... Экземпляр может существовать без переменной и даже некоторое время вообще без ссылок. А так - ссылка может быть из поля или массива и т.п.
РЕШЕНИЕ: убрал объяснение этого термина

- [x] 1.2 - "железо", может чем то заменить?
РЕШЕНИЕ: заменил на "устройство"

- [x] В ссылках на примеры - всё ещё тире, в то время как в папках я уже поменял на какой то из dash -эй (не помню какой).
РЕШЕНИЕ: исправил.

Остальные моменты, которые были не спорные а просто неправильные - в этом коммите:

**Comment by AIexandrKotov** [comment]
1.2 устройство

**Comment by SunSerega** [comment]
Ну типа уже давно всё норм вроде...
