### ISSUE TITLE
Separate project into several branches: OpenGL, OpenCL, master

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [SunSerega/POCGL#5]

**Comment by SunSerega** [comment]
Я думал над этим, но не вижу особых преимуществ

**Comment by SunSerega** [comment]
В общем ес чо пиши об этом в вк, чтоб тут не висело лишний раз...

**Comment by EmilyGraceSeville7cf** [comment]
The reason why it's better to do is hidding developing process of some project parts untill it isn't completed.

**Comment by SunSerega** [comment]
Я уже объяснял, они уже тут спрятаны, в этом отдельном репозитории. А рабочие релизы идут в репе паскаля и его установщиках.

Кроме того, если тут что то не работает - я обычно быстро исправляю.
И если тут появляется значительное улучшение - я сразу кидаю пулл в репу паскаля.
Да, лишние задержки с такой организацией труда есть. Но мне некуда спешить.
