### ISSUE TITLE
Рефакторинг кода в OpenCLABC

### ISSUE THREAD

**Issue by Alvin-Seville** [SunSerega/POCGL#6]
- `__NativUtils` - правильнее - `NativeUtils`, использование нижних подчёркиваний в качестве префикса или суффикса - плохая практика.
- Не у всех членов `__NativeUtils` есть модификаторы доступа, хорошая практика явно указывать модификаторы доступа.

```pascal
    static function GCHndAlloc(o: object) :=
    CopyToUnm(GCHandle.Alloc(o));
```

Я бы написал так:

```pascal
    static function GCHndAlloc(o: object) :=
      CopyToUnm(GCHandle.Alloc(o));
```
Кстати, и убрал бы лишние пустые строки перед и после последнего члена типа.

**Comment by SunSerega** [comment]
> `__NativUtils` - правильнее - `NativeUtils`

Нет, это внутренний тип. Такое вообще бы в `implementation` засунуть, но тогда придётся реализацию многих методов тоже туда отправить.

Все внутренние типы в `OpenCLABC` имеют префикс `__` и описание `///--`. Но описание добавляется только в релизе, чтоб пока пишу модуль - анализатор кода работал.

> Не у всех членов `__NativeUtils` есть модификаторы доступа

А это плохо да... Сейчас проверю.

---

Остальное - вкусовщина. Дополнительные пробелы и пустые строки не влияют на видимый интерфейс (особенно считая что это внутренний тип), так что пока во всём модуле так - всё правильно.

**Comment by SunSerega** [comment]
> А это плохо да... Сейчас проверю.

Не не у всех, а ни у одного. Это не одно и то же.

Теперь когда посмотрел - вспомнил, так и задумано. Из внутренний типов - только `__EventList` имеет модификаторы доступа. И только потому что это врапер.

**Comment by Alvin-Seville** [comment]
> Нет, это внутренний тип. Такое вообще бы в implementation засунуть, но тогда придётся реализацию многих методов тоже туда отправить.

Все внутренние типы в OpenCLABC имеют префикс __ и описание ///--. Но описание добавляется только в релизе, чтоб пока пишу модуль - анализатор кода работал.

Да, правильнее поместить в `implementation`.

**Comment by SunSerega** [comment]
> Внутренние типы не должны быть доступны никак извне модуля. Точнее, даже зная что за внутренний тип (его имя) пользователь не должен мочь до него достучаться.

Ну, по крайней мере этот тип не может никому помешать, благодаря префиксу и описанию. Ну а доступ к типу можно получить и из `implementation`, если хотеть, потому что рефлекция.

> Тогда вполне понятный вопрос - чем модификаторы доступа так мешали, что Вы их не стали ставить? Какая разница то, `wrapper` или нет?

Особо ничего, просто лишние буквы, отвлекающие от сути.

`__EventList` содержит поля которые не должны использоваться извне (кроме нескольких особых случаев). В том что показывает анализатор кода по точек - имеются значки с которыми легко отличить приватные и публичные вещи. Это мелочь, но приятно.

**Comment by Alvin-Seville** [comment]
> Ну, по крайней мере этот тип не может никому помешать, благодаря префиксу и описанию. Ну а доступ к типу можно получить и из implementation, если хотеть, потому что рефлекция.

Рефлексия на то и рефлексия - от неё мало что спасёт. Поэтому, тут вообще упоминание про неё лишние.

> Особо ничего, просто лишние буквы, отвлекающие от сути.

Тогда, почему в других местах данные "буквы" не считаются лишними?

**Comment by SunSerega** [comment]
Я никуда не спешил. Весь код хорошо продуман перед написанием и особенно коммитом. И особенно по сравнению с предыдущим комментом.

И я уже говорил, я переписываю всё что мне не нравится. И я горжусь этим. Кишки `OpenCLABC` были переписаны как минимум пару десятков раз.

---

Использовать рефлекцию не сложнее и ничем не особеннее копания в кишках модуля.
А вопрос "почему другим местах (в не_внутренних типах) модификаторы доступа не лишние" содержит ответ в себе же при минимальном перефразировании (слова в скобках).

Не трать моё время на вопросы, на которые можешь ответить сам, подумав больше 5 минут.

**Comment by Alvin-Seville** [comment]
> Не трать моё время на вопросы, на которые можешь ответить сам, подумав больше 5 минут.

Если Вам так не хочется уделять время каким-то мелочам, то прямо так и скажите. Хотя бы, будете честны перед самим собой и пользователями.

**Comment by AIexandrKotov** [comment]
Нифига вы срач из ерунды развели. Мне кажется, что один человек из Владивостока снова хернёй занимается. Мы можем продолжить данный срач, но неизменно будет одно: Сергей продолжит писать код так, как ему хочется. Если тебе и дальше интересно тратить своё время (хотя, ты получаешь от этого удАвольствие, потому что тебе нечем заняться), то ВПЕРЁД, ЗАСРИ ЗДЕСЬ ВСЁ СВОИМ ОЧЕНЬ ВАЖНЫМ МНЕНИЕМ. Если же ты меня услышал, то предлагаю на этом моменте закрыть дискуссию.

**Comment by Alvin-Seville** [comment]
Продолжайте игнорировать мелочи... А Ваши маты - на скриншоте, и я с удовольствием им воспользуюсь при удобной ситуации.

**Comment by SunSerega** [comment]
А я и забыл что у тебя тут есть права)) Ну в принципе пусть, так проще чем продолжать читать как перевирают мои слова при каждой попытке объяснить...
